#!/usr/bin/env php
<?php

include('../src/Sendmail.php');
include('../src/ForwardToSmtp.php');
include('../src/ForwardToFile.php');

$forwarders = [
	new ForwardToFile(__DIR__ . '/mails.json'),
	/*
	new ForwardToSmtp([
		'host' => 'ssl://smtp.gmail.com:465',
		'user' => 'YOUR_USERNAME',
		'pass' => 'YOUR_PASSWORD',
	]),
	*/
];

new Sendmail(file_get_contents('php://stdin'), $forwarders);
